//--------------------Includes para probar-------------------------------------
#include "component.h"
#include "Defines.h"
//#include "functions.h"
#include "item.h"
//#include "slot.h"
#include "itemFactory.h"
#include "world.h"
#include "actorFactory.h"
#include "actor.h"